/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.namrita.productApplication;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Product p = new Product("Apple", "Produce-Fruits", "1.99");
        p.printProductDescription();
    }
}
